package io.github.mcdev.core.aw

object AwDiagnosticCodes {
    const val INVALID_DIRECTIVE = "AW_INVALID_DIRECTIVE"
    const val INVALID_KIND = "AW_INVALID_KIND"
    const val UNRESOLVED_CLASS = "AW_UNRESOLVED_CLASS"
    const val UNRESOLVED_MEMBER = "AW_UNRESOLVED_MEMBER"
    const val INVALID_DESCRIPTOR = "AW_INVALID_DESCRIPTOR"
    const val DUPLICATE_ENTRY = "AW_DUPLICATE_ENTRY"
    const val MUTABLE_ON_NON_FIELD = "AW_MUTABLE_ON_NON_FIELD"
    const val EXTENDABLE_INVALID_TARGET = "AW_EXTENDABLE_INVALID_TARGET"
    const val NAMESPACE_MISMATCH = "AW_NAMESPACE_MISMATCH"
}
