package io.github.mcdev.core.mixinextras

object MixinExtrasDiagnosticCodes {
    const val HANDLER_SIGNATURE_MISMATCH = "MIXINEXTRAS_HANDLER_SIGNATURE_MISMATCH"
    const val MISSING_OPERATION_PARAMETER = "MIXINEXTRAS_MISSING_OPERATION_PARAMETER"
    const val WRONG_OPERATION_GENERIC = "MIXINEXTRAS_WRONG_OPERATION_GENERIC"
    const val WRONG_ORIGINAL_VALUE_TYPE = "MIXINEXTRAS_WRONG_ORIGINAL_VALUE_TYPE"
    const val WRONG_RETURN_TYPE = "MIXINEXTRAS_WRONG_RETURN_TYPE"
    const val UNSUPPORTED_EXPRESSION_CONTEXT = "MIXINEXTRAS_UNSUPPORTED_EXPRESSION_CONTEXT"
    const val MISSING_EXPRESSION_ANNOTATION = "MIXINEXTRAS_MISSING_EXPRESSION_ANNOTATION"
}
