package io.github.mcdev.core.mixinextras

object MixinExtrasDiagnosticCodes {
    const val INVALID_DEFINITION = "MIXINEXTRAS_INVALID_DEFINITION"
    const val HANDLER_SIGNATURE_MISMATCH = "MIXINEXTRAS_HANDLER_SIGNATURE_MISMATCH"
    const val MISSING_OPERATION_PARAMETER = "MIXINEXTRAS_MISSING_OPERATION_PARAMETER"
    const val WRONG_OPERATION_GENERIC = "MIXINEXTRAS_WRONG_OPERATION_GENERIC"
    const val WRONG_ORIGINAL_VALUE_TYPE = "MIXINEXTRAS_WRONG_ORIGINAL_VALUE_TYPE"
    const val WRONG_RETURN_TYPE = "MIXINEXTRAS_WRONG_RETURN_TYPE"
    const val UNSUPPORTED_EXPRESSION_CONTEXT = "MIXINEXTRAS_UNSUPPORTED_EXPRESSION_CONTEXT"
    const val MISSING_EXPRESSION_ANNOTATION = "MIXINEXTRAS_MISSING_EXPRESSION_ANNOTATION"
    const val INVALID_SHARE_PARAMETER_TYPE = "MIXINEXTRAS_INVALID_SHARE_PARAMETER_TYPE"
    const val UNSUPPORTED_SUGAR_PARAMETER = "MIXINEXTRAS_UNSUPPORTED_SUGAR_PARAMETER"
    const val WRAP_WITH_CONDITION_INVALID_TARGET = "MIXINEXTRAS_WRAP_WITH_CONDITION_INVALID_TARGET"
    const val WRAP_WITH_CONDITION_POPPED_NON_VOID = "MIXINEXTRAS_WRAP_WITH_CONDITION_POPPED_NON_VOID"
    const val WRONG_OPERATION_CALL_ARGUMENTS = "MIXINEXTRAS_WRONG_OPERATION_CALL_ARGUMENTS"
    const val LOCAL_CAPTURE_NOT_FOUND = "MIXINEXTRAS_LOCAL_CAPTURE_NOT_FOUND"
    const val LOCAL_CAPTURE_AMBIGUOUS = "MIXINEXTRAS_LOCAL_CAPTURE_AMBIGUOUS"
    const val SHARE_TYPE_CONFLICT = "MIXINEXTRAS_SHARE_TYPE_CONFLICT"
    const val WRAP_METHOD_STATIC_MISMATCH = "MIXINEXTRAS_WRAP_METHOD_STATIC_MISMATCH"
    const val WRAP_METHOD_INVALID_TARGET = "MIXINEXTRAS_WRAP_METHOD_INVALID_TARGET"
}
